#!/usr/bin/env bash

# release.sh prepares mod files from src to Zomboid/Workshop folder.
#
# Copyright (c) 2026 outdead.
# Use of this source code is governed by the MIT license.
#
# DO NOT EDIT THIS FILE!

MOD_NAME="LogExtender"

# MOD_VERSION of current mod.
# Follows semantic versioning, SEE: http://semver.org/.
MOD_VERSION="$1"
if [ -z "${MOD_VERSION}" ]; then echo "MOD_VERSION is not set. Use ./release.sh 0.0.0 stage" >&2; exit 1; fi

STAGE="$2"
if [ -z "${STAGE}" ]; then STAGE="prod"; fi

case ${STAGE} in
  local|test|prod)
    echo "[ INFO ] Preparing ${STAGE} release v${MOD_VERSION}" ;;
  *)
    echo "[  ER  ] Incorrect stage \"${STAGE}\"" >&2; exit 1  ;;
esac

if [ "${STAGE}" == "test" ]; then MOD_NAME="${MOD_NAME}Test"; fi
if [ "${STAGE}" == "local" ]; then MOD_NAME="${MOD_NAME}Local"; fi

RELEASE_NAME="${MOD_NAME}-${MOD_VERSION}"

RELEASE_DIR_WORKSHOP=".tmp/release/${RELEASE_NAME}"
RELEASE_DIR_WORKSHOP_MOD_NAME="${RELEASE_DIR_WORKSHOP}/Contents/mods/${MOD_NAME}"

ZOMBOID_WORKSHOP_DIR=~/Zomboid/Workshop
ZOMBOID_WORKSHOP_MOD_DIR=${ZOMBOID_WORKSHOP_DIR}/"${MOD_NAME}"

WORKDIR=.tmp/release

function remove_old_release() {
  rm -rf ${WORKDIR:?}
  rm -rf ${ZOMBOID_WORKSHOP_MOD_DIR:?}
}

function create_folders() {
  mkdir -p ${WORKDIR}
  touch ${WORKDIR}/checksum.txt
}

function make_release() {
  local dir_workshop=${RELEASE_DIR_WORKSHOP}
  local dir_mod_home="${RELEASE_DIR_WORKSHOP_MOD_NAME}"

  local dir_common="${dir_mod_home}/common"
  local dir_42="${dir_mod_home}/42"

  mkdir -p "${dir_mod_home}"
  mkdir -p "${dir_common}"
  mkdir -p "${dir_42}"

  cp workshop/"${STAGE}"/workshop.txt "${dir_workshop}"
  cp workshop/"${STAGE}"/mod.info "${dir_42}"

  sed -i -r "s/id=${MOD_NAME}/id=${MOD_NAME}/g" "${dir_42}/mod.info"

  cp workshop/preview.png "${dir_workshop}/preview.png"
  cp workshop/poster.png "${dir_42}"
  cp src/b42 -r "${dir_42}/media"

  find "${dir_42}/media" -name '*_test.lua' -type f -delete

  cp LICENSE "${dir_42}"
  cp README.md "${dir_42}"
  cp CHANGELOG.md "${dir_42}"
  cp VERSION "${dir_42}"
}

function compress_release() {
  local dir_workshop=${RELEASE_DIR_WORKSHOP}

  cd "${dir_workshop}/Contents/mods/" && {
    tar -zcvf "../../../${RELEASE_NAME}.tar.gz" "${MOD_NAME}"
    zip -r "../../../${RELEASE_NAME}.zip" "${MOD_NAME}"
  }

  cd ../../../ && {
    md5sum "${RELEASE_NAME}.tar.gz" >> checksum.txt;
    md5sum "${RELEASE_NAME}.zip" >> checksum.txt;
    cd ../../;
  }
}

function install_release() {
  cp -r ${WORKDIR:?}/"${RELEASE_NAME:?}" ${ZOMBOID_WORKSHOP_MOD_DIR}
  rm -r ${WORKDIR:?}/"${RELEASE_NAME}"
}

remove_old_release && \
  create_folders && \
  make_release && \
  compress_release && \
  install_release
